### ISSUE TITLE
Text input focus border is red

### ISSUE THREAD

**Issue by jonathaningram** [govau/uikit#306]
I know that colour isn't everything, but when a text input is completed and you tab through and focus them, their border is red which as a user makes me think it's invalid. What's the reason for this?

**Comment by alex-page** [comment]
@jonathaningram The dark orange on white and bright orange on dark was done to maximise colour contrast from the link colour and text color. While still being accessible.

Currently we are missing error messages which we would strongly recommend to provide with a form that has errors. @TrebBrennan has done a rough mockup of this and is a great suggestion for a new component.

**Comment by jonathaningram** [comment]
@alex-page yeah the bright orange on dark is cool, but the dark orange on white just looks red to me. And I know that's very subjective, but aren't 99% of website forms using red borders/lines to indicate error states?

![image](https://user-images.githubusercontent.com/626664/36408140-9d8fdb0e-1657-11e8-8423-db48d29344c6.png)

![image](https://user-images.githubusercontent.com/626664/36408146-a42157cc-1657-11e8-8a0a-bb04a4ec9cab.png)

**Comment by TrebBrennan** [comment]
I think this is good feedback, it's been niggling thought for a while so it's probably something we need to consider.

We picked a focus colour that standouts quite dramatically against the blue hues of the default palette.  So that it's very obvious, similar to https://www.gov.uk/ but theirs doesn't pass a 3:1 contrast ratio which we would like to.

I think @alex-page's idea of a colour which has less implied meaning is a good one; I'll add an enhancement label to this issue and assign myself... but if anyone want to take a stab at it, it would be appreciated.

**Comment by dominikwilkowski** [comment]
Sorry folks I know this is not ideal but we just moved all suggestions and discussions to our community forum. I copied your text there. Please join us there to keep the discussion going. this is a very good point @jonathaningram has here and @TrebBrennan will be looking into this soon.

Moved to: https://community.service.gov.au/t/text-inputs

**Comment by alex-page** [comment]
@jonathaningram This is fixed and live. We also added the offset back.

**Comment by jonathaningram** [comment]
@alex-page

![image](https://media.giphy.com/media/l41lNp8dHpfaJE25O/giphy.gif)
