### ISSUE TITLE
Radio focus state to border the circle instead of a square

### ISSUE THREAD

**Issue by mikey0000** [govau/uikit#509]
# Feature Request
- [x] I’ve read and understood the [Contributing guidelines](https://github.com/govau/uikit/blob/master/CONTRIBUTING.md) and have done my best effort to follow them.
- [x] I’ve read and agree to the [Code of Conduct](https://github.com/govau/uikit/blob/master/CODE_OF_CONDUCT.md).
- [x] I’ve searched for any related issues and avoided creating a duplicate issue.
- [x] I've searched the [community forums](https://community.digital.gov.au/c/designsystem) to check for related issues or feature requests

## Is this feature request relating to an existing component? Please describe.
- Component name: control-input
- Component version: 2.1.6

Outline (on focus accessibility) doesn't allow radius, instead use box-shadow, there is css in control-input for radio which has border-radius 50% which does nothing to outline which results in a square focus outline against a round radio button.

**Comment by alex-page** [comment]
Hi @mikey0000 the reasoning for this originally was because `box-shadow` is not supported in legacy browsers. `box-shadow` also requires a little bit more processing power by the computer ( not a huge problem however ). 

That being said we really like the appearance of the text input and radio buttons by the gov uk team which use this technique.
https://design-system.service.gov.uk/components/radios/

I see this as a valuable change for the design aesthetic however it will require a fallback for legacy browsers. I would like to investigate this and see how simple it would be to implement, noting we have some pretty complicated things going on in the control input component with svg swapping on different states.

**Comment by alex-page** [comment]
The main reason is when svgs stop working they fallback to default form elements on old browsers.
