### ISSUE TITLE
Incorrect footer role tag

### ISSUE THREAD

**Issue by adamzerella** [govau/uikit#514]
Validating the site using https://validator.w3.org/nu/?doc=https%3A%2F%2Fdesignsystem.gov.au%2F it appears that the `footer` HTML element is using an unnecessary `role="content-info"` tag

# Bug Report

- [x] I’ve read and understood the [Contributing guidelines](https://github.com/govau/uikit/blob/master/CONTRIBUTING.md) and have done my best effort to follow them.
- [x] I’ve read and agree to the [Code of Conduct](https://github.com/govau/uikit/blob/master/CODE_OF_CONDUCT.md).
- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

**Comment by alex-page** [comment]
This includes updating the design system website and the footer component.

**Comment by sukhrajghuman** [comment]
The HTML5 `footer` element defines a `contentinfo` landmark when its context is the body element

The HTML5 `footer` element is not considered a `contentinfo` landmark when it is descendant of any of following elements:
- `article`
- `aside`
- `main`
- `nav`
- `section`

Since we don't know how our users are going to be using the `footer` tag, we should exclude the `role="contentinfo"` from the component.

Thoughts @alex-page ?

**Comment by alex-page** [comment]
Is there a link to this justification?

**Comment by sukhrajghuman** [comment]
@alex-page yup added

**Comment by alex-page** [comment]
This has been fixed in #228 and can be seen here:
https://designsystem.gov.au/components/footer/rationale/
